### ISSUE TITLE
Review accessibility of menu open/close behaviour

### ISSUE THREAD

**Issue by paulrobertlloyd** [24ways/frontend#1]
While the basic behaviour of the navigation menu is complete, and there is some rudimentary accessibility assistance, this could likely be improved.

The main outstanding issue concerns focusable content:
* When the menu is close, links and the search field remain focusable, even though they are not visible.
* When the menu is open, links within the main body of the page remain focusable.
* When the menu opens, should an element within it receive focus? Which element?

**Comment by mattmachell** [comment]
Tab order seems a bit out of kilter if I activate the menu by tabbing to it and hitting enter. If I then tab off the close menu button I'm now focused on I end up back on article links. I'd expect to move into the menu focusing on the first menu item, or focus on the menu as a whole when I activate the menu.

**Comment by plfstr** [comment]
To address points 1 (and perhaps 2) you might want to look at the [inert](https://github.com/WICG/inert#the-case-for-inert-as-a-primitive) property.
