### ISSUE TITLE
npm install babel-core babel-loader --save-dev

### ISSUE THREAD

**Issue by sabsaxo** [24ways/frontend#14]
I had to run this command manually to get it up and running ... due to this error:

`Error: Cannot find module 'babel-core'`

It still burps stuff like: ✘ No matching route found for /favicon.ico, though ...

**Comment by paulrobertlloyd** [comment]
[This commit](https://github.com/24ways/frontend/commit/ffd1d58d04dac5d5c11a166cae582917b5718878) should have fixed this issue.
