### ISSUE TITLE
All links to components are broke when running from localhost (missing .html)?

### ISSUE THREAD

**Issue by sabsaxo** [24ways/frontend#15]
When running npm build and going to http://localhost/24ways/www the page loads fine initially, but links to all components are broke (missing the .html extension).

Now, do one have to do other arbitrary stuff to just make this work out of the box?

**Comment by sabsaxo** [comment]
Create an .htaccess file (or modify the existing one, if any) and add:

`Options +MultiViews`

But please state that somewhere in the docs ... I at least wasn't able to find it anywhere.

**Comment by ChucKN0risK** [comment]
@sabsaxo I did create a .htaccess file in the `www/` folder however the issue remains :/

**Comment by sabsaxo** [comment]
Haven't fiddled with this in a while. Waiting for V2 ...

**Comment by bryanhidalgo** [comment]
You need to change:` fractal.web.set('builder.urls.ext', null)`; to  `fractal.web.set('builder.urls.ext', '.html');`

**Comment by blaasvaer** [comment]
Well, then one may wonder why setting this kind of stuff to null as default ...

**Comment by paulrobertlloyd** [comment]
Closing this issue as it relates more to Fractal than this particular component library, and solutions have been provided in the comments above.
