### ISSUE TITLE
Page corner effect broken in Firefox

### ISSUE THREAD

**Issue by paulrobertlloyd** [24ways/frontend#19]
Background positioning of page corner image is miscalculated in Firefox (57.0.3, Windows 10).

![24ways-hover](https://user-images.githubusercontent.com/813383/34500295-05bb0d92-f002-11e7-90bd-56b477e2a00f.png)

**Comment by gnclmorais** [comment]
Looks fine @ Firefox Dev Edition (71.0b7 (64-bit):
![image](https://user-images.githubusercontent.com/385232/70459991-435c2c80-1aad-11ea-9538-28b9391f2124.png)

Is this still an issue?

**Comment by paulrobertlloyd** [comment]
Oooh, looks like its fixed. 🎉

Will close this issue, for now. Thanks for the spot, @gnclmorais!
