### ISSUE TITLE
README: Clone Repo URL is not correct

### ISSUE THREAD

**Issue by caraya** [24ways/frontend#5]
When trying to clone the repository using the instructions on the README I get the following error

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

For remote access the URL should be https://github.com/24ways/frontend.git

**Comment by paulrobertlloyd** [comment]
Have added instructions for cloning using alternative HTTPS method to the README. Thanks for reporting this issue.
